// Auto-generated by scripts/sync-branding.mjs. Do not edit manually.

pub const PRODUCT_NAME: &str = "MesoClaw";
pub const SLUG: &str = "mesoclaw";
pub const REVERSE_DOMAIN: &str = "com.sprklai";
pub const BUNDLE_IDENTIFIER: &str = "com.sprklai.mesoclaw";
pub const ICON_ASSET_PATH: &str = "/mesoclaw-lobster.png";
pub const KEYCHAIN_SERVICE: &str = "com.sprklai.mesoclaw";
pub const CREDENTIALS_SERVICE: &str = "com.mesoclaw.credentials";
pub const STRONGHOLD_CLIENT_NAME: &str = "mesoclaw-secrets";
pub const STRONGHOLD_VAULT_PASSWORD: &str = "mesoclaw-secure-vault";
pub const OPENROUTER_HTTP_REFERER: &str = "https://mesoclaw.app";
pub const OPENROUTER_TITLE: &str = "mesoclaw";
pub const TRAY_TOOLTIP: &str = "mesoclaw";
pub const SKILLS_CONFIG_DIR_NAME: &str = "mesoclaw";
