name: Feature Request
description: Propose a new feature or enhancement for MesoClaw
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe the problem you're trying to solve.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who is affected?
      placeholder: As a user who [does X], I often struggle with [Y] because [Z].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] User can ...
        - [ ] System correctly handles ...
        - [ ] Documentation is updated
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to Have
        - Should Have
        - Must Have
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
    validations:
      required: false
