// Auto-generated by scripts/sync-branding.mjs. Do not edit manually.

export const APP_IDENTITY = {
  "productName": "MesoClaw",
  "slug": "mesoclaw",
  "reverseDomain": "com.sprklai",
  "bundleIdentifier": "com.sprklai.mesoclaw",
  "iconAssetPath": "/mesoclaw-lobster.png",
  "keychainService": "com.sprklai.mesoclaw",
  "credentialsService": "com.mesoclaw.credentials",
  "strongholdClientName": "mesoclaw-secrets",
  "strongholdVaultPassword": "mesoclaw-secure-vault",
  "openRouterHttpReferer": "https://mesoclaw.app",
  "openRouterTitle": "mesoclaw",
  "trayTooltip": "mesoclaw",
  "skillsConfigDirName": "mesoclaw"
} as const;
