/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PromptGeneratorRouteImport } from './routes/prompt-generator'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LifecycleRouteImport } from './routes/lifecycle'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptGeneratorRoute = PromptGeneratorRouteImport.update({
  id: '/prompt-generator',
  path: '/prompt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleRoute = LifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/lifecycle': typeof LifecycleRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/lifecycle': typeof LifecycleRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/lifecycle': typeof LifecycleRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/prompt-generator': typeof PromptGeneratorRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/channels'
    | '/chat'
    | '/lifecycle'
    | '/logs'
    | '/memory'
    | '/onboarding'
    | '/prompt-generator'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/channels'
    | '/chat'
    | '/lifecycle'
    | '/logs'
    | '/memory'
    | '/onboarding'
    | '/prompt-generator'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/channels'
    | '/chat'
    | '/lifecycle'
    | '/logs'
    | '/memory'
    | '/onboarding'
    | '/prompt-generator'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChannelsRoute: typeof ChannelsRoute
  ChatRoute: typeof ChatRoute
  LifecycleRoute: typeof LifecycleRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  PromptGeneratorRoute: typeof PromptGeneratorRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-generator': {
      id: '/prompt-generator'
      path: '/prompt-generator'
      fullPath: '/prompt-generator'
      preLoaderRoute: typeof PromptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle': {
      id: '/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof LifecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChannelsRoute: ChannelsRoute,
  ChatRoute: ChatRoute,
  LifecycleRoute: LifecycleRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  PromptGeneratorRoute: PromptGeneratorRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
